=== MPDL-Collections/INGe/src/main/xsd/soap/organizational-unit/0.3/organizational-unit-path-list.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:organizational-unit-path-list="http://www.escidoc.de/schemas/organizationalunitpathlist/0.3" targetNamespace="http://www.escidoc.de/schemas/organizationalunitpathlist/0.3" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import schemaLocation="http://www.escidoc.de/schemas/soap/common/0.3/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="organizational-unit-path-list">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="organizational-unit-path">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="organizational-unit-ref">
								<xs:complexType>
									<xs:attribute name="objid"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MPDL-Collections/INGe/common_logic/src/test/resources/xmltransforming/component/transformAffiliationTest/organizational-unit-path-list_sample1.xml
<?xml version="1.0" encoding="UTF-8"?><organizational-unit-path-list:organizational-unit-path-list xmlns:organizational-unit-path-list="${xsd.soap.ou.oupathlist}" xmlns:organizational-unit-reference="${xsd.soap.ou.ouref}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.escidoc.de/schemas/organizationalunitpathlist/0.3 ../../../../misc/xsd/soap/organizational-unit/0.3/organizational-unit-path-list.xsd" xmlns:xlink="http://www.w3.org/1999/xlink">
	<organizational-unit-path-list:organizational-unit-path>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:1234"/>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:5678"/>
	</organizational-unit-path-list:organizational-unit-path>
	<organizational-unit-path-list:organizational-unit-path>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:9101"/>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:1121"/>
	</organizational-unit-path-list:organizational-unit-path>
	<organizational-unit-path-list:organizational-unit-path>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:3141"/>
		<organizational-unit-reference:organizational-unit-ref xlink:href="escidoc:5161"/>
	</organizational-unit-path-list:organizational-unit-path>
</organizational-unit-path-list:organizational-unit-path-list>
